POST http://localhost:4000/auth/refresh-tokens
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImVtYWlsIjoidXNlcm5hbWU0QGdtYWlsLmNvbSIsImlhdCI6MTc1Mzk1MTk1MCwiZXhwIjoxNzUzOTU1NTUwLCJhdWQiOiJsb2NhbGhvc3Q6NDAwMCIsImlzcyI6ImxvY2FsaG9zdDo0MDAwIn0.Xp3Hojf6NG9mGmkKbDsOKIJ85ZVPtpvej5390aAcjxE

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsImlhdCI6MTc1Mzk1MTk1MCwiZXhwIjoxNzU0MDM4MzUwLCJhdWQiOiJsb2NhbGhvc3Q6NDAwMCIsImlzcyI6ImxvY2FsaG9zdDo0MDAwIn0.5Fj40iwnrzvhXlv7ghm8_8lGSgaEOc-TE-CFBwrq14A"
}
